### ISSUE TITLE
It would be nice to integrate with the apps

### ISSUE THREAD

**Issue by chrissearle** [javaBin/Switcharoo#32]
Simplest version - some json endpoint to get current active messages.

**Comment by bendiksolheim** [comment]
You can get all existing "slides" for an event at this endpoint: https://www.switcharoo.party/data/{event}. An event is a conference, so the slides for JZ2019 can be fetched from here: https://www.switcharoo.party/data/10

But Switcharoo is also used for other conferences, so you can’t rely on the ID for JavaZone slides. Or rather, you don’t know the next ID before something like 1 day before JavaZone happens.

Also, I suspect this request has something to do with the new app? Most slides published by Switcharoo are .webm files, so they are hard to use outside Switcharoo itself.

**Comment by chrissearle** [comment]
OK - the webm - no - not so interested. I was thinking more along the lines of "we have a room change for ..." or "we have a time change for ..." - these messages get displayed somewhere at the conference and I assumed that was also switcharoo? It's those kind I was looking for - are they also just webm?

**Comment by bendiksolheim** [comment]
Yeah, are also from Switcharoo. And they _can_ be text. But there is no way of knowing, really. Switcharoo supports text, image and video slides, and it’s up to the person managing it to select one. If a slide is made in a hurry (urgent room change, and so on), they might be made of text, but they are mostly made as videos if I recall correctly.

So.. right now the content in Switcharoo is not really structured, it’s just a bunch of blobs. Text is more or less a fallback.

**Comment by chrissearle** [comment]
OK. Then I don't think this is the correct place to go looking :) Thanks for the info.
